# Generated by Django 2.2.5 on 2020-04-06 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cereated',
            new_name='created',
        ),
    ]
